### ISSUE TITLE
Fragment doesn't take full screen 

### ISSUE THREAD

**Issue by tarungarg95** [MMIL/Zealicon-App#2]

**Comment by anant-dev** [comment]
Send me the screenshot for this issue .

**Comment by tarungarg95** [comment]
![whatsapp image 2017-03-13 at 11 42 33 pm 2](https://cloud.githubusercontent.com/assets/20770699/23868823/e6e9f656-0846-11e7-93bd-2092e38eaf5b.jpeg)
![whatsapp image 2017-03-13 at 11 42 33 pm 1](https://cloud.githubusercontent.com/assets/20770699/23868827/e9f7f5b4-0846-11e7-887f-a41456f05590.jpeg)
![whatsapp image 2017-03-13 at 11 42 33 pm](https://cloud.githubusercontent.com/assets/20770699/23868833/ec98f552-0846-11e7-9eff-469b0dbd69aa.jpeg)

**Comment by anant-dev** [comment]
I have updated the code Do check once again
